### ISSUE TITLE
Unsupported container type: 'rancher'

### ISSUE THREAD

**Issue by digitalLumberjack** [rawmind0/rancher-vamp#1]
Hi pal, i tried to start vamp from your catalog, and i got an error that seems weird : 
Unsupported container type: 'rancher'.

Do you have any idea ?

Thanks for the hard work :) 

```

21/11/2016 19:52:44pidfile '/opt/vamp/logs/vamp.pid' does not exist
21/11/2016 19:52:44'vamp-core' start: /opt/vamp/bin/vamp-service.sh
21/11/2016 19:52:45Mon Nov 21 18:52:45 UTC 2016 - [ Starting vamp... ]
21/11/2016 19:52:45Mon Nov 21 18:52:45 UTC 2016 - [ Generating vamp configuration... ]
21/11/2016 19:52:45Mon Nov 21 18:52:45 UTC 2016 - [ Redirecting vamp log to stdout... ]
21/11/2016 19:52:45rm: can't remove '/opt/vamp/logs/vamp.out': No such file or directory
21/11/2016 19:52:45rm: can't remove '/opt/vamp/nohup.out': No such file or directory
21/11/2016 19:52:45nohup: appending output to nohup.out
21/11/2016 19:52:45'vamp-core' started
21/11/2016 19:52:4818:52:48.153 | INFO  | io.vamp.bootstrap.Vamp                   |                                          | 
21/11/2016 19:52:48██╗   ██╗ █████╗ ███╗   ███╗██████╗
21/11/2016 19:52:48██║   ██║██╔══██╗████╗ ████║██╔══██╗
21/11/2016 19:52:48██║   ██║███████║██╔████╔██║██████╔╝
21/11/2016 19:52:48╚██╗ ██╔╝██╔══██║██║╚██╔╝██║██╔═══╝
21/11/2016 19:52:48 ╚████╔╝ ██║  ██║██║ ╚═╝ ██║██║
21/11/2016 19:52:48  ╚═══╝  ╚═╝  ╚═╝╚═╝     ╚═╝╚═╝
21/11/2016 19:52:48                       version 0.8.5
21/11/2016 19:52:48                       by magnetic.io
21/11/2016 19:52:48
21/11/2016 19:52:48    
21/11/2016 19:52:4818:52:48.153 | INFO  | io.vamp.bootstrap.Vamp                   |                                          | 
21/11/2016 19:52:48██╗   ██╗ █████╗ ███╗   ███╗██████╗
21/11/2016 19:52:48██║   ██║██╔══██╗████╗ ████║██╔══██╗
21/11/2016 19:52:48██║   ██║███████║██╔████╔██║██████╔╝
21/11/2016 19:52:48╚██╗ ██╔╝██╔══██║██║╚██╔╝██║██╔═══╝
21/11/2016 19:52:48 ╚████╔╝ ██║  ██║██║ ╚═╝ ██║██║
21/11/2016 19:52:48  ╚═══╝  ╚═╝  ╚═╝╚═╝     ╚═╝╚═╝
21/11/2016 19:52:48                       version 0.8.5
21/11/2016 19:52:48                       by magnetic.io
21/11/2016 19:52:48
21/11/2016 19:52:48    
21/11/2016 19:52:4818:52:48.232 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:zookeeper.version=3.4.7-1713338, built on 11/09/2015 04:32 GMT
21/11/2016 19:52:4818:52:48.232 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:zookeeper.version=3.4.7-1713338, built on 11/09/2015 04:32 GMT
21/11/2016 19:52:4818:52:48.233 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:host.name=vamp_vamp_1
21/11/2016 19:52:4818:52:48.233 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:host.name=vamp_vamp_1
21/11/2016 19:52:4818:52:48.233 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:java.version=1.8.0_92
21/11/2016 19:52:4818:52:48.233 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:java.version=1.8.0_92
21/11/2016 19:52:4818:52:48.233 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:java.vendor=Oracle Corporation
21/11/2016 19:52:4818:52:48.233 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:java.vendor=Oracle Corporation
21/11/2016 19:52:4818:52:48.233 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:java.home=/opt/jre1.8.0_92
21/11/2016 19:52:4818:52:48.233 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:java.home=/opt/jre1.8.0_92
21/11/2016 19:52:4818:52:48.234 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:java.class.path=/opt/vamp/jar/vamp-0.8.5.jar
21/11/2016 19:52:4818:52:48.234 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:java.class.path=/opt/vamp/jar/vamp-0.8.5.jar
21/11/2016 19:52:4818:52:48.234 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
21/11/2016 19:52:4818:52:48.234 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:java.library.path=/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
21/11/2016 19:52:4818:52:48.234 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:java.io.tmpdir=/tmp
21/11/2016 19:52:4818:52:48.234 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:java.io.tmpdir=/tmp
21/11/2016 19:52:4818:52:48.234 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:java.compiler=<NA>
21/11/2016 19:52:4818:52:48.234 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:java.compiler=<NA>
21/11/2016 19:52:4818:52:48.235 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:os.name=Linux
21/11/2016 19:52:4818:52:48.235 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:os.name=Linux
21/11/2016 19:52:4818:52:48.235 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:os.arch=amd64
21/11/2016 19:52:4818:52:48.235 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:os.arch=amd64
21/11/2016 19:52:4818:52:48.235 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:os.version=4.4.21-rancher
21/11/2016 19:52:4818:52:48.235 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:os.version=4.4.21-rancher
21/11/2016 19:52:4818:52:48.235 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:user.name=vamp
21/11/2016 19:52:4818:52:48.235 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:user.name=vamp
21/11/2016 19:52:4818:52:48.235 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:user.home=/opt/vamp
21/11/2016 19:52:4818:52:48.235 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:user.home=/opt/vamp
21/11/2016 19:52:4818:52:48.236 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:user.dir=/opt/vamp
21/11/2016 19:52:4818:52:48.236 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Client environment:user.dir=/opt/vamp
21/11/2016 19:52:4818:52:48.237 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Initiating client connection, connectString=zookeeper:2181 sessionTimeout=5000 watcher=io.vamp.persistence.kv.AsyncZooKeeperClientImpl$$anon$7@52127db8
21/11/2016 19:52:4818:52:48.237 | INFO  | org.apache.zookeeper.ZooKeeper           |                                          | Initiating client connection, connectString=zookeeper:2181 sessionTimeout=5000 watcher=io.vamp.persistence.kv.AsyncZooKeeperClientImpl$$anon$7@52127db8
21/11/2016 19:52:4818:52:48.304 | ERROR | io.vamp.common.notification.Notification |                                          | Unsupported container type: 'rancher'.
21/11/2016 19:52:4818:52:48.304 | ERROR | io.vamp.common.notification.Notification |                                          | Unsupported container type: 'rancher'.
21/11/2016 19:52:48Exception in thread "main" java.lang.ExceptionInInitializerError
21/11/2016 19:52:48	at io.vamp.bootstrap.Boot.main(Boot.scala)
21/11/2016 19:52:48Caused by: io.vamp.common.notification.NotificationErrorException: Unsupported container type: 'rancher'.
21/11/2016 19:52:48	at io.vamp.common.notification.LoggingNotificationProvider$class.reportException(NotificationProvider.scala:38)
21/11/2016 19:52:48	at io.vamp.container_driver.ContainerDriverBootstrap$.reportException(ContainerDriverBootstrap.scala:10)
21/11/2016 19:52:48	at io.vamp.common.notification.NotificationProvider$class.throwException(NotificationProvider.scala:14)
21/11/2016 19:52:48	at io.vamp.container_driver.ContainerDriverBootstrap$.throwException(ContainerDriverBootstrap.scala:10)
21/11/2016 19:52:48	at io.vamp.container_driver.ContainerDriverBootstrap$.createActors(ContainerDriverBootstrap.scala:27)
21/11/2016 19:52:48	at io.vamp.common.akka.Bootstrap$class.run(Bootstrap.scala:11)
21/11/2016 19:52:48	at io.vamp.container_driver.ContainerDriverBootstrap$.run(ContainerDriverBootstrap.scala:10)
21/11/2016 19:52:48	at io.vamp.bootstrap.Vamp$$anonfun$2.apply(Vamp.scala:56)
21/11/2016 19:52:48	at io.vamp.bootstrap.Vamp$$anonfun$2.apply(Vamp.scala:56)
21/11/2016 19:52:48	at scala.collection.immutable.List.foreach(List.scala:381)
21/11/2016 19:52:48	at io.vamp.bootstrap.Vamp$class.$init$(Vamp.scala:56)
21/11/2016 19:52:48	at io.vamp.bootstrap.Boot$.<init>(Boot.scala:3)
21/11/2016 19:52:48	at io.vamp.bootstrap.Boot$.<clinit>(Boot.scala)
21/11/2016 19:52:48	... 1 more
21/11/2016 19:52:4818:52:48.372 | INFO  | i.v.p.kv.AsyncZooKeeperClientImpl        |                                          | Attempting to connect to zookeeper servers zookeeper:2181
21/11/2016 19:52:4818:52:48.372 | INFO  | i.v.p.kv.AsyncZooKeeperClientImpl        |                                          | Attempting to connect to zookeeper servers zookeeper:2181
21/11/2016 19:52:4818:52:48.392 | INFO  | org.apache.zookeeper.ClientCnxn          |                                          | Opening socket connection to server 10.42.58.113/10.42.58.113:2181. Will not attempt to authenticate using SASL (unknown error)
21/11/2016 19:52:4818:52:48.392 | INFO  | org.apache.zookeeper.ClientCnxn          |                                          | Opening socket connection to server 10.42.58.113/10.42.58.113:2181. Will not attempt to authenticate using SASL (unknown error)
21/11/2016 19:52:4818:52:48.412 | INFO  | org.apache.zookeeper.ClientCnxn          |                                          | Socket connection established to 10.42.58.113/10.42.58.113:2181, initiating session
21/11/2016 19:52:4818:52:48.412 | INFO  | org.apache.zookeeper.ClientCnxn          |                                          | Socket connection established to 10.42.58.113/10.42.58.113:2181, initiating session
21/11/2016 19:52:4818:52:48.501 | INFO  | org.apache.zookeeper.ClientCnxn          |                                          | Session establishment complete on server 10.42.58.113/10.42.58.113:2181, sessionid = 0x25886ddc1410000, negotiated timeout = 5000
21/11/2016 19:52:4818:52:48.501 | INFO  | org.apache.zookeeper.ClientCnxn          |                                          | Session establishment complete on server 10.42.58.113/10.42.58.113:2181, sessionid = 0x25886ddc1410000, negotiated timeout = 5000
21/11/2016 19:53:46'vamp-core' process is running with pid 20
21/11/2016 19:53:46'vamp-core' zombie check succeeded
21/11/2016 19:53:46Socket test failed for [::1]:8080 -- Connection refused
21/11/2016 19:53:46Socket test failed for [127.0.0.1]:8080 -- Connection refused
21/11/2016 19:53:46'vamp-core' failed protocol test [DEFAULT] at [localhost]:8080 [TCP/IP] -- Connection refused
21/11/2016 19:54:46'vamp-core' process is running with pid 20
21/11/2016 19:54:46'vamp-core' zombie check succeeded
21/11/2016 19:54:46Socket test failed for [::1]:8080 -- Connection refused
21/11/2016 19:54:46Socket test failed for [127.0.0.1]:8080 -- Connection refused
21/11/2016 19:54:46'vamp-core' failed protocol test [DEFAULT] at [localhost]:8080 [TCP/IP] -- Connection refused
21/11/2016 19:55:46'vamp-core' process is running with pid 20
21/11/2016 19:55:46'vamp-core' zombie check succeeded
21/11/2016 19:55:46Socket test failed for [::1]:8080 -- Connection refused
21/11/2016 19:55:46Socket test failed for [127.0.0.1]:8080 -- Connection refused
21/11/2016 19:55:46'vamp-core' failed protocol test [DEFAULT] at [localhost]:8080 [TCP/IP] -- Connection refused
```

**Comment by olafmol** [comment]
Might be unrelated, but worth a try: could you see if following these instructions make Vamp run on Rancher? http://vamp.io/documentation/installation/rancher/

**Comment by rawmind0** [comment]
Hi @digitalLumberjack, thanks to try it... :)

in alpine-vamp:0.8.5, vamp was installed from https://bintray.com/artifact/download/magnetic-io/downloads/vamp/vamp-0.8.5.jar jar file. 
@olafmol may be this jar doesn't have built-in rancher support??

I created a 0.9.1 version downloading jar file https://bintray.com/artifact/download/magnetic-io/downloads/vamp/vamp-0.9.1.jar and updated rancher catalog. Could you try it, please??

BTW,  this repo is deprecated...In future could you please, open issues in https://github.com/rawmind0/alpine-vamp ??

Thanks, best regards...

**Comment by rawmind0** [comment]
One more think....

I've try to update alpine-vamp-ui with the version 0.9.1, but i get build errors... @olafmol , could you help me with that, please?? https://github.com/rawmind0/alpine-vamp-ui is the Dockerfile....

I close that issue, please...Reopen it in the correct repo if you need... :)

Thanks, best regards...
